In [ ]:
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]
array_list = np.array(object = list_)

In [ ]:
type(list_)

list

In [ ]:
type(array_list)

numpy.ndarray

yes there is difference b/w the data types of variables list_ and array_list

In [5]:
for x in np.nditer(array_list):
  print(x)

1
2
3
4
5


In [7]:
for x in list_:
  print(x)

1
2
3
4
5


In [9]:
array_list = np.array(object = list_, dtype = int)
array_list


array([1, 2, 3, 4, 5])

In [12]:
print(type(array_list))
print(type(list_))

<class 'numpy.ndarray'>
<class 'list'>


In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
np.shape(num_array)

(2, 3)

In [20]:
np.size(num_array)

6

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])